name: CI Monorepo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build docker
        run: docker compose build
      - name: Run tests
        run: docker compose run --rm backend pytest
